<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Modules\Configuration\Sgol.Configuration.csproj" />
    <ProjectReference Include="..\Modules\Generation\Sgol.Generation.csproj" />
    <ProjectReference Include="..\Modules\Identity\Sgol.Identity.csproj" />
    <ProjectReference Include="..\Modules\Organization\Sgol.Organization.csproj" />
    <ProjectReference Include="..\Modules\Planning\Sgol.Planning.csproj" />
    <ProjectReference Include="..\Sgol.BuildingBlocks\Sgol.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
