<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Modules\Continuity\Sgol.Continuity.csproj" />
    <ProjectReference Include="..\Sgol.Web\Sgol.Web.csproj" />
  </ItemGroup>
</Project>
