<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Assignment\Sgol.Assignment.csproj" />
    <ProjectReference Include="..\..\src\Modules\Generation\Sgol.Generation.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Identity\Sgol.Identity.csproj" />
    <ProjectReference Include="..\..\src\Modules\Organization\Sgol.Organization.csproj" />
    <ProjectReference Include="..\..\src\Modules\Planning\Sgol.Planning.csproj" />
    <ProjectReference Include="..\..\src\Sgol.Web\Sgol.Web.csproj" />
    <ProjectReference Include="..\..\src\Sgol.Worker\Sgol.Worker.csproj" />
  </ItemGroup>
</Project>
