// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sgol.Web.Infrastructure.Persistence;

#nullable disable

namespace Sgol.Web.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SgolDbContext))]
    [Migration("20260902231629_AddConfigurationReleases")]
    partial class AddConfigurationReleases
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sgol.Configuration.Contracts.ConfigurationRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_id");

                    b.Property<int?>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .IsUnique()
                        .HasDatabaseName("IX_configuration_release_one_current")
                        .HasFilter("status = 'VIGENTE'");

                    b.HasIndex("PublishedBy");

                    b.HasIndex("SupersedesId")
                        .IsUnique()
                        .HasDatabaseName("IX_configuration_release_supersedes_id")
                        .HasFilter("supersedes_id IS NOT NULL");

                    b.HasIndex("BranchId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("IX_configuration_release_branch_id_version_no")
                        .HasFilter("version_no IS NOT NULL");

                    b.ToTable("configuration_release", null, t =>
                        {
                            t.HasCheckConstraint("CK_configuration_release_lifecycle", "(status = 'BORRADOR' AND effective_from IS NULL AND effective_to IS NULL AND reason IS NULL AND supersedes_id IS NULL) OR (status = 'VIGENTE' AND effective_from IS NOT NULL AND effective_to IS NULL AND btrim(reason) <> '') OR (status = 'SUSTITUIDA' AND effective_from IS NOT NULL AND effective_to > effective_from AND btrim(reason) <> '')");

                            t.HasCheckConstraint("CK_configuration_release_not_self_superseding", "supersedes_id IS NULL OR supersedes_id <> id");

                            t.HasCheckConstraint("CK_configuration_release_publication", "(status = 'BORRADOR' AND version_no IS NULL AND published_by IS NULL AND published_at IS NULL) OR (status IN ('VIGENTE', 'SUSTITUIDA') AND version_no > 0 AND published_by IS NOT NULL AND published_at IS NOT NULL)");

                            t.HasCheckConstraint("CK_configuration_release_row_version", "row_version > 0");

                            t.HasCheckConstraint("CK_configuration_release_status", "status IN ('BORRADOR', 'VIGENTE', 'SUSTITUIDA')");
                        });
                });

            modelBuilder.Entity("Sgol.Organization.Contracts.AvailabilityDayVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date")
                        .HasColumnName("local_date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_id");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("SupersedesId")
                        .IsUnique()
                        .HasFilter("supersedes_id IS NOT NULL");

                    b.HasIndex("PersonId", "BranchId", "LocalDate")
                        .IsUnique()
                        .HasFilter("status = 'VIGENTE'");

                    b.ToTable("availability_day_version", null, t =>
                        {
                            t.HasCheckConstraint("CK_availability_day_version_row_version", "row_version >= 1");

                            t.HasCheckConstraint("CK_availability_day_version_status", "status IN ('VIGENTE', 'HISTORICA')");
                        });
                });

            modelBuilder.Entity("Sgol.Organization.Contracts.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("branch", null, t =>
                        {
                            t.HasCheckConstraint("CK_branch_mvp_code", "code = 'LOR-001'");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("019d2d67-2c00-7000-8000-000000000001"),
                            Code = "LOR-001",
                            Name = "Loretta",
                            Status = "ACTIVA",
                            TimeZone = "America/Mexico_City"
                        });
                });

            modelBuilder.Entity("Sgol.Organization.Contracts.EmploymentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("PositionText")
                        .HasColumnType("text")
                        .HasColumnName("position_text");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("ShiftText")
                        .HasColumnType("text")
                        .HasColumnName("shift_text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_id");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("SupersedesId")
                        .IsUnique()
                        .HasFilter("supersedes_id IS NOT NULL");

                    b.HasIndex("PersonId", "BranchId")
                        .IsUnique()
                        .HasFilter("valid_to IS NULL");

                    b.ToTable("employment_version", null, t =>
                        {
                            t.HasCheckConstraint("CK_employment_version_interval", "valid_to IS NULL OR valid_to >= valid_from");

                            t.HasCheckConstraint("CK_employment_version_status", "status IN ('ACTIVA', 'INACTIVA')");
                        });
                });

            modelBuilder.Entity("Sgol.Organization.Contracts.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("StableCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stable_code");

                    b.HasKey("Id");

                    b.HasIndex("StableCode")
                        .IsUnique();

                    b.ToTable("person", null, t =>
                        {
                            t.HasCheckConstraint("CK_person_stable_code_not_blank", "btrim(stable_code) <> ''");
                        });
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Auditing.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<JsonDocument>("AfterData")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_data");

                    b.Property<JsonDocument>("BeforeData")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_data");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("RequestId")
                        .HasColumnType("text")
                        .HasColumnName("request_id");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_type");

                    b.Property<string>("SourceIpHash")
                        .HasColumnType("character(64)")
                        .HasColumnName("source_ip_hash");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId", "OccurredAt")
                        .IsDescending(false, true);

                    b.HasIndex("BranchId", "OccurredAt")
                        .IsDescending(false, true);

                    b.HasIndex("ResourceType", "ResourceId", "OccurredAt")
                        .IsDescending(false, false, true);

                    b.ToTable("audit_event", (string)null);
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("MfaEnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mfa_enrolled_at");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.DirectionBootstrapMarker", b =>
                {
                    b.Property<bool>("Singleton")
                        .HasColumnType("boolean")
                        .HasColumnName("singleton");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.HasKey("Singleton");

                    b.ToTable("direction_bootstrap", null, t =>
                        {
                            t.HasCheckConstraint("CK_direction_bootstrap_singleton", "singleton");
                        });
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.IdempotencyRecord", b =>
                {
                    b.Property<string>("Scope")
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("request_hash");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_type");

                    b.Property<int>("ResponseCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Scope", "Key");

                    b.ToTable("idempotency_record", (string)null);
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.IdentityCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.ToTable("identity_credential", (string)null);
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.RoleAssignmentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_code");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("SupersedesId");

                    b.HasIndex("UserId", "BranchId")
                        .IsUnique()
                        .HasFilter("status = 'ACTIVO'");

                    b.ToTable("role_assignment_version", null, t =>
                        {
                            t.HasCheckConstraint("CK_role_assignment_version_interval", "(status = 'ACTIVO' AND valid_to IS NULL) OR (status = 'SUSTITUIDO' AND valid_to IS NOT NULL AND valid_to >= valid_from)");

                            t.HasCheckConstraint("CK_role_assignment_version_role_code", "role_code IN ('DIRECCION', 'ADMINISTRACION', 'SUBCOORDINACION', 'PISO_VENTAS')");

                            t.HasCheckConstraint("CK_role_assignment_version_status", "status IN ('ACTIVO', 'SUSTITUIDO')");
                        });
                });

            modelBuilder.Entity("Sgol.Configuration.Contracts.ConfigurationRelease", b =>
                {
                    b.HasOne("Sgol.Organization.Contracts.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Web.Infrastructure.Persistence.Bootstrap.AppUser", null)
                        .WithMany()
                        .HasForeignKey("PublishedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sgol.Configuration.Contracts.ConfigurationRelease", null)
                        .WithOne()
                        .HasForeignKey("Sgol.Configuration.Contracts.ConfigurationRelease", "SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sgol.Organization.Contracts.AvailabilityDayVersion", b =>
                {
                    b.HasOne("Sgol.Organization.Contracts.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Web.Infrastructure.Persistence.Bootstrap.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Organization.Contracts.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Organization.Contracts.AvailabilityDayVersion", null)
                        .WithMany()
                        .HasForeignKey("SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sgol.Organization.Contracts.EmploymentVersion", b =>
                {
                    b.HasOne("Sgol.Organization.Contracts.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Organization.Contracts.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Organization.Contracts.EmploymentVersion", null)
                        .WithMany()
                        .HasForeignKey("SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.AppUser", b =>
                {
                    b.HasOne("Sgol.Organization.Contracts.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.IdentityCredential", b =>
                {
                    b.HasOne("Sgol.Web.Infrastructure.Persistence.Bootstrap.AppUser", null)
                        .WithOne()
                        .HasForeignKey("Sgol.Web.Infrastructure.Persistence.Bootstrap.IdentityCredential", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.RoleAssignmentVersion", b =>
                {
                    b.HasOne("Sgol.Organization.Contracts.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Web.Infrastructure.Persistence.Bootstrap.RoleAssignmentVersion", null)
                        .WithMany()
                        .HasForeignKey("SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sgol.Web.Infrastructure.Persistence.Bootstrap.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
