// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sgol.Web.Infrastructure.Persistence;

#nullable disable

namespace Sgol.Web.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SgolDbContext))]
    [Migration("20260901223021_EnforceLorettaBranchScope")]
    partial class EnforceLorettaBranchScope
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sgol.Organization.Contracts.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("branch", null, t =>
                        {
                            t.HasCheckConstraint("CK_branch_mvp_code", "code = 'LOR-001'");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("019d2d67-2c00-7000-8000-000000000001"),
                            Code = "LOR-001",
                            Name = "Loretta",
                            Status = "ACTIVA",
                            TimeZone = "America/Mexico_City"
                        });
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Auditing.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<JsonDocument>("AfterData")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_data");

                    b.Property<JsonDocument>("BeforeData")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_data");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("RequestId")
                        .HasColumnType("text")
                        .HasColumnName("request_id");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_type");

                    b.Property<string>("SourceIpHash")
                        .HasColumnType("character(64)")
                        .HasColumnName("source_ip_hash");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId", "OccurredAt")
                        .IsDescending(false, true);

                    b.HasIndex("BranchId", "OccurredAt")
                        .IsDescending(false, true);

                    b.HasIndex("ResourceType", "ResourceId", "OccurredAt")
                        .IsDescending(false, false, true);

                    b.ToTable("audit_event", (string)null);
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("MfaEnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mfa_enrolled_at");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.DirectionBootstrapMarker", b =>
                {
                    b.Property<bool>("Singleton")
                        .HasColumnType("boolean")
                        .HasColumnName("singleton");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.HasKey("Singleton");

                    b.ToTable("direction_bootstrap", null, t =>
                        {
                            t.HasCheckConstraint("CK_direction_bootstrap_singleton", "singleton");
                        });
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.EmploymentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("PositionText")
                        .HasColumnType("text")
                        .HasColumnName("position_text");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("ShiftText")
                        .HasColumnType("text")
                        .HasColumnName("shift_text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_id");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("SupersedesId");

                    b.HasIndex("PersonId", "BranchId")
                        .IsUnique()
                        .HasFilter("status = 'ACTIVA'");

                    b.ToTable("employment_version", (string)null);
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.IdentityCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.ToTable("identity_credential", (string)null);
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("StableCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stable_code");

                    b.HasKey("Id");

                    b.HasIndex("StableCode")
                        .IsUnique();

                    b.ToTable("person", (string)null);
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.RoleAssignmentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("SupersedesId");

                    b.HasIndex("UserId", "BranchId")
                        .IsUnique()
                        .HasFilter("status = 'ACTIVO'");

                    b.ToTable("role_assignment_version", null, t =>
                        {
                            t.HasCheckConstraint("CK_role_assignment_version_role_code", "role_code IN ('DIRECCION', 'ADMINISTRACION', 'SUBCOORDINACION', 'PISO_VENTAS')");
                        });
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.AppUser", b =>
                {
                    b.HasOne("Sgol.Web.Infrastructure.Persistence.Bootstrap.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.EmploymentVersion", b =>
                {
                    b.HasOne("Sgol.Organization.Contracts.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Web.Infrastructure.Persistence.Bootstrap.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Web.Infrastructure.Persistence.Bootstrap.EmploymentVersion", null)
                        .WithMany()
                        .HasForeignKey("SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.IdentityCredential", b =>
                {
                    b.HasOne("Sgol.Web.Infrastructure.Persistence.Bootstrap.AppUser", null)
                        .WithOne()
                        .HasForeignKey("Sgol.Web.Infrastructure.Persistence.Bootstrap.IdentityCredential", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.RoleAssignmentVersion", b =>
                {
                    b.HasOne("Sgol.Organization.Contracts.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Web.Infrastructure.Persistence.Bootstrap.RoleAssignmentVersion", null)
                        .WithMany()
                        .HasForeignKey("SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sgol.Web.Infrastructure.Persistence.Bootstrap.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
