// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sgol.Web.Infrastructure.Persistence;

#nullable disable

namespace Sgol.Web.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SgolDbContext))]
    [Migration("20260903225522_AddEligibilityEvaluations")]
    partial class AddEligibilityEvaluations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sgol.Assignment.Contracts.EligibilityCandidate", b =>
                {
                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluation_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<int?>("ActiveLoad")
                        .HasColumnType("integer")
                        .HasColumnName("active_load");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_eligible");

                    b.Property<DateTimeOffset?>("LastAutoAssignmentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_auto_assignment_at");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<JsonDocument>("Reasons")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reasons");

                    b.Property<string>("StableCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stable_code");

                    b.HasKey("EvaluationId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("eligibility_candidate", null, t =>
                        {
                            t.HasCheckConstraint("CK_eligibility_candidate_hu016_fields", "active_load IS NULL AND last_auto_assignment_at IS NULL AND rank IS NULL");

                            t.HasCheckConstraint("CK_eligibility_candidate_reasons", "jsonb_typeof(reasons) = 'array' AND reasons <@ '[\"PERSONA_INACTIVA\",\"EMPLEO_NO_VIGENTE\",\"SUCURSAL_NO_COINCIDE\",\"ROL_ACTIVO_AUSENTE\",\"ROL_REQUERIDO_NO_COINCIDE\",\"DISPONIBILIDAD_AUSENTE\",\"DISPONIBILIDAD_NO_POSITIVA\",\"TURNO_NO_COINCIDE\"]'::jsonb AND ((is_eligible AND jsonb_array_length(reasons) = 0) OR (NOT is_eligible AND jsonb_array_length(reasons) > 0))");

                            t.HasCheckConstraint("CK_eligibility_candidate_stable_code", "btrim(stable_code) <> ''");
                        });
                });

            modelBuilder.Entity("Sgol.Assignment.Contracts.EligibilityEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("EligibilityDate")
                        .HasColumnType("date")
                        .HasColumnName("eligibility_date");

                    b.Property<string>("EligibilityDateSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("eligibility_date_source");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<Guid>("EvaluationRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluation_request_id");

                    b.Property<JsonDocument>("InputSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_snapshot");

                    b.Property<Guid>("ObligationId")
                        .HasColumnType("uuid")
                        .HasColumnName("obligation_id");

                    b.Property<Guid>("PolicyVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_version_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result");

                    b.Property<Guid?>("WinnerPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_person_id");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationRequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_eligibility_evaluation_request");

                    b.HasIndex("PolicyVersionId");

                    b.HasIndex("WinnerPersonId");

                    b.HasIndex("ObligationId", "EvaluatedAt", "Id");

                    b.ToTable("eligibility_evaluation", null, t =>
                        {
                            t.HasCheckConstraint("CK_eligibility_evaluation_date_source", "eligibility_date_source IN ('MANUAL_REQUEST','SCHEDULED_OCCURRENCE')");

                            t.HasCheckConstraint("CK_eligibility_evaluation_no_winner", "winner_person_id IS NULL");

                            t.HasCheckConstraint("CK_eligibility_evaluation_result", "result IN ('CANDIDATOS_ELEGIBLES','SIN_CANDIDATO_ELEGIBLE')");

                            t.HasCheckConstraint("CK_eligibility_evaluation_snapshot_object", "jsonb_typeof(input_snapshot) = 'object'");
                        });
                });

            modelBuilder.Entity("Sgol.Configuration.Contracts.ActivationRuleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BasedOnId")
                        .HasColumnType("uuid")
                        .HasColumnName("based_on_id");

                    b.Property<DateTimeOffset?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("mode");

                    b.Property<string>("OriginKeySchema")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("origin_key_schema");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<JsonDocument>("Schedule")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("schedule");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_id");

                    b.Property<Guid>("TaskDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_definition_id");

                    b.Property<Guid>("TaskDefinitionVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_definition_version_id");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.HasKey("Id");

                    b.HasIndex("BasedOnId");

                    b.HasIndex("SupersedesId")
                        .IsUnique()
                        .HasDatabaseName("IX_activation_rule_version_supersedes_id")
                        .HasFilter("supersedes_id IS NOT NULL");

                    b.HasIndex("TaskDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("IX_activation_rule_version_one_current")
                        .HasFilter("status = 'VIGENTE'");

                    b.HasIndex("ReleaseId", "TaskDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("IX_activation_rule_version_release_task");

                    b.HasIndex("TaskDefinitionId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("IX_activation_rule_version_number");

                    b.HasIndex("TaskDefinitionVersionId", "TaskDefinitionId")
                        .HasDatabaseName("IX_activation_rule_version_exact_task_version");

                    b.ToTable("activation_rule_version", null, t =>
                        {
                            t.HasCheckConstraint("CK_activation_rule_version_lifecycle", "(status = 'BORRADOR' AND effective_from IS NULL AND effective_to IS NULL AND reason IS NULL AND supersedes_id IS NULL) OR (status = 'VIGENTE' AND effective_from IS NOT NULL AND effective_to IS NULL AND btrim(reason) <> '') OR (status = 'SUSTITUIDA' AND effective_from IS NOT NULL AND effective_to > effective_from AND btrim(reason) <> '')");

                            t.HasCheckConstraint("CK_activation_rule_version_manual_schedule", "(mode = 'MANUAL' AND schedule = 'null'::jsonb) OR (mode = 'RECURRENTE' AND jsonb_typeof(schedule) = 'object')");

                            t.HasCheckConstraint("CK_activation_rule_version_mode", "mode IN ('MANUAL','RECURRENTE')");

                            t.HasCheckConstraint("CK_activation_rule_version_not_self_superseding", "supersedes_id IS NULL OR supersedes_id <> id");

                            t.HasCheckConstraint("CK_activation_rule_version_number", "version_no > 0");

                            t.HasCheckConstraint("CK_activation_rule_version_origin_schema", "origin_key_schema IN ('MANUAL_REFERENCE_V1','WORKING_DAY_WINDOW_V1','SERVICE_DUE_DATE_REFERENCE_V1')");

                            t.HasCheckConstraint("CK_activation_rule_version_row_version", "row_version > 0");

                            t.HasCheckConstraint("CK_activation_rule_version_schedule_shape", "(task_definition_id = '019d3a10-0005-7000-8000-000000000005'::uuid AND schedule = '{\"kind\":\"WORKING_DAY_WINDOWS\",\"localTimes\":[\"12:00\",\"17:00\"],\"timeZone\":\"America/Mexico_City\",\"workingDaysOnly\":true}'::jsonb) OR (task_definition_id IN ('019d3a10-0007-7000-8000-000000000007'::uuid,'019d3a10-0008-7000-8000-000000000008'::uuid,'019d3a10-0011-7000-8000-000000000011'::uuid,'019d3a10-0018-7000-8000-000000000018'::uuid,'019d3a10-0092-7000-8000-000000000092'::uuid,'019d3a10-0093-7000-8000-000000000093'::uuid) AND schedule = 'null'::jsonb) OR (task_definition_id = '019d3a10-0026-7000-8000-000000000026'::uuid AND schedule ? 'localTime' AND schedule->>'localTime' ~ '^(?:[01][0-9]|2[0-3]):[0-5][0-9]$' AND schedule - 'localTime' = '{\"kind\":\"BUSINESS_DAYS_BEFORE_DUE_DATE\",\"businessDaysBefore\":3,\"timeZone\":\"America/Mexico_City\",\"adjustDueDateToPreviousBusinessDay\":true}'::jsonb)");

                            t.HasCheckConstraint("CK_activation_rule_version_status", "status IN ('BORRADOR', 'VIGENTE', 'SUSTITUIDA')");

                            t.HasCheckConstraint("CK_activation_rule_version_task_policy", "(task_definition_id = '019d3a10-0005-7000-8000-000000000005'::uuid AND mode = 'RECURRENTE' AND origin_key_schema = 'WORKING_DAY_WINDOW_V1') OR (task_definition_id IN ('019d3a10-0007-7000-8000-000000000007'::uuid,'019d3a10-0008-7000-8000-000000000008'::uuid,'019d3a10-0011-7000-8000-000000000011'::uuid,'019d3a10-0018-7000-8000-000000000018'::uuid,'019d3a10-0092-7000-8000-000000000092'::uuid,'019d3a10-0093-7000-8000-000000000093'::uuid) AND mode = 'MANUAL' AND origin_key_schema = 'MANUAL_REFERENCE_V1') OR (task_definition_id = '019d3a10-0026-7000-8000-000000000026'::uuid AND mode = 'RECURRENTE' AND origin_key_schema = 'SERVICE_DUE_DATE_REFERENCE_V1')");
                        });
                });

            modelBuilder.Entity("Sgol.Configuration.Contracts.CalendarDayVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("day_type");

                    b.Property<DateTimeOffset?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_working_day");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date")
                        .HasColumnName("local_date");

                    b.Property<string>("PendingReason")
                        .HasColumnType("text")
                        .HasColumnName("pending_reason");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_id");

                    b.HasKey("Id");

                    b.HasIndex("SupersedesId")
                        .IsUnique()
                        .HasDatabaseName("IX_calendar_day_version_supersedes_id")
                        .HasFilter("supersedes_id IS NOT NULL");

                    b.HasIndex("BranchId", "LocalDate")
                        .IsUnique()
                        .HasDatabaseName("IX_calendar_day_version_one_current")
                        .HasFilter("status = 'VIGENTE'");

                    b.HasIndex("ReleaseId", "LocalDate")
                        .IsUnique()
                        .HasDatabaseName("IX_calendar_day_version_release_id_local_date")
                        .HasFilter("status = 'BORRADOR'");

                    b.ToTable("calendar_day_version", null, t =>
                        {
                            t.HasCheckConstraint("CK_calendar_day_version_day_type", "day_type IN ('LABORABLE', 'FESTIVO', 'CIERRE_EXTRAORDINARIO')");

                            t.HasCheckConstraint("CK_calendar_day_version_lifecycle", "(status = 'BORRADOR' AND effective_from IS NULL AND effective_to IS NULL AND reason IS NULL AND supersedes_id IS NULL) OR (status = 'VIGENTE' AND effective_from IS NOT NULL AND effective_to IS NULL AND btrim(reason) <> '') OR (status = 'SUSTITUIDA' AND effective_from IS NOT NULL AND effective_to > effective_from AND btrim(reason) <> '')");

                            t.HasCheckConstraint("CK_calendar_day_version_not_self_superseding", "supersedes_id IS NULL OR supersedes_id <> id");

                            t.HasCheckConstraint("CK_calendar_day_version_pending_reason", "(status = 'BORRADOR' AND btrim(pending_reason) <> '') OR (status IN ('VIGENTE', 'SUSTITUIDA') AND pending_reason IS NULL)");

                            t.HasCheckConstraint("CK_calendar_day_version_row_version", "row_version > 0");

                            t.HasCheckConstraint("CK_calendar_day_version_status", "status IN ('BORRADOR', 'VIGENTE', 'SUSTITUIDA')");

                            t.HasCheckConstraint("CK_calendar_day_version_working_consistency", "(day_type = 'LABORABLE' AND is_working_day) OR (day_type IN ('FESTIVO', 'CIERRE_EXTRAORDINARIO') AND NOT is_working_day)");
                        });
                });

            modelBuilder.Entity("Sgol.Configuration.Contracts.ConfigurationRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_id");

                    b.Property<int?>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .IsUnique()
                        .HasDatabaseName("IX_configuration_release_one_current")
                        .HasFilter("status = 'VIGENTE'");

                    b.HasIndex("PublishedBy");

                    b.HasIndex("SupersedesId")
                        .IsUnique()
                        .HasDatabaseName("IX_configuration_release_supersedes_id")
                        .HasFilter("supersedes_id IS NOT NULL");

                    b.HasIndex("BranchId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("IX_configuration_release_branch_id_version_no")
                        .HasFilter("version_no IS NOT NULL");

                    b.ToTable("configuration_release", null, t =>
                        {
                            t.HasCheckConstraint("CK_configuration_release_lifecycle", "(status = 'BORRADOR' AND effective_from IS NULL AND effective_to IS NULL AND reason IS NULL AND supersedes_id IS NULL) OR (status = 'VIGENTE' AND effective_from IS NOT NULL AND effective_to IS NULL AND btrim(reason) <> '') OR (status = 'SUSTITUIDA' AND effective_from IS NOT NULL AND effective_to > effective_from AND btrim(reason) <> '')");

                            t.HasCheckConstraint("CK_configuration_release_not_self_superseding", "supersedes_id IS NULL OR supersedes_id <> id");

                            t.HasCheckConstraint("CK_configuration_release_publication", "(status = 'BORRADOR' AND version_no IS NULL AND published_by IS NULL AND published_at IS NULL) OR (status IN ('VIGENTE', 'SUSTITUIDA') AND version_no > 0 AND published_by IS NOT NULL AND published_at IS NOT NULL)");

                            t.HasCheckConstraint("CK_configuration_release_row_version", "row_version > 0");

                            t.HasCheckConstraint("CK_configuration_release_status", "status IN ('BORRADOR', 'VIGENTE', 'SUSTITUIDA')");
                        });
                });

            modelBuilder.Entity("Sgol.Configuration.Contracts.EligibilityPolicyVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BasedOnId")
                        .HasColumnType("uuid")
                        .HasColumnName("based_on_id");

                    b.Property<DateTimeOffset?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<string>("RequiredRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("required_role");

                    b.Property<string>("RequiredShift")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("required_shift");

                    b.Property<bool>("RequiresAvailability")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_availability");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_id");

                    b.Property<Guid>("TaskDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_definition_id");

                    b.Property<Guid>("TaskDefinitionVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_definition_version_id");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.HasKey("Id");

                    b.HasIndex("BasedOnId");

                    b.HasIndex("SupersedesId")
                        .IsUnique()
                        .HasDatabaseName("IX_eligibility_policy_version_supersedes_id")
                        .HasFilter("supersedes_id IS NOT NULL");

                    b.HasIndex("TaskDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("IX_eligibility_policy_version_one_current")
                        .HasFilter("status = 'VIGENTE'");

                    b.HasIndex("ReleaseId", "TaskDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("IX_eligibility_policy_version_release_task");

                    b.HasIndex("TaskDefinitionId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("IX_eligibility_policy_version_number");

                    b.HasIndex("TaskDefinitionVersionId", "TaskDefinitionId")
                        .HasDatabaseName("IX_eligibility_policy_version_exact_task_version");

                    b.ToTable("eligibility_policy_version", null, t =>
                        {
                            t.HasCheckConstraint("CK_eligibility_policy_version_availability", "requires_availability");

                            t.HasCheckConstraint("CK_eligibility_policy_version_lifecycle", "(status = 'BORRADOR' AND effective_from IS NULL AND effective_to IS NULL AND reason IS NULL AND supersedes_id IS NULL) OR (status = 'VIGENTE' AND effective_from IS NOT NULL AND effective_to IS NULL AND btrim(reason) <> '') OR (status = 'SUSTITUIDA' AND effective_from IS NOT NULL AND effective_to > effective_from AND btrim(reason) <> '')");

                            t.HasCheckConstraint("CK_eligibility_policy_version_not_self_superseding", "supersedes_id IS NULL OR supersedes_id <> id");

                            t.HasCheckConstraint("CK_eligibility_policy_version_number", "version_no > 0");

                            t.HasCheckConstraint("CK_eligibility_policy_version_role", "required_role IN ('ADMINISTRACION','SUBCOORDINACION','PISO_VENTAS')");

                            t.HasCheckConstraint("CK_eligibility_policy_version_row_version", "row_version > 0");

                            t.HasCheckConstraint("CK_eligibility_policy_version_shift", "required_shift IS NULL");

                            t.HasCheckConstraint("CK_eligibility_policy_version_status", "status IN ('BORRADOR', 'VIGENTE', 'SUSTITUIDA')");
                        });
                });

            modelBuilder.Entity("Sgol.Configuration.Contracts.TaskDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TaskCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("task_code");

                    b.HasKey("Id");

                    b.HasIndex("TaskCode")
                        .IsUnique()
                        .HasDatabaseName("IX_task_definition_task_code");

                    b.ToTable("task_definition", null, t =>
                        {
                            t.HasCheckConstraint("CK_task_definition_mvp_code", "task_code IN ('TAR-0005','TAR-0007','TAR-0008','TAR-0011','TAR-0018','TAR-0026','TAR-0092','TAR-0093')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("019d3a10-0005-7000-8000-000000000005"),
                            Name = "Monitorear el avance de ventas y activar acciones correctivas",
                            TaskCode = "TAR-0005"
                        },
                        new
                        {
                            Id = new Guid("019d3a10-0007-7000-8000-000000000007"),
                            Name = "Liberar la mercancía al vencer un Separado de Cortesía",
                            TaskCode = "TAR-0007"
                        },
                        new
                        {
                            Id = new Guid("019d3a10-0008-7000-8000-000000000008"),
                            Name = "Resolver una controversia de asignación de venta con base en evidencia",
                            TaskCode = "TAR-0008"
                        },
                        new
                        {
                            Id = new Guid("019d3a10-0011-7000-8000-000000000011"),
                            Name = "Gestionar la reparación o el cambio de una garantía autorizada después de 90 días",
                            TaskCode = "TAR-0011"
                        },
                        new
                        {
                            Id = new Guid("019d3a10-0018-7000-8000-000000000018"),
                            Name = "Montar o actualizar exhibiciones conforme al planograma y la zonificación",
                            TaskCode = "TAR-0018"
                        },
                        new
                        {
                            Id = new Guid("019d3a10-0026-7000-8000-000000000026"),
                            Name = "Programar y realizar el pago de servicios básicos",
                            TaskCode = "TAR-0026"
                        },
                        new
                        {
                            Id = new Guid("019d3a10-0092-7000-8000-000000000092"),
                            Name = "Coordinar la recepción de mercancía contra la nota de envío",
                            TaskCode = "TAR-0092"
                        },
                        new
                        {
                            Id = new Guid("019d3a10-0093-7000-8000-000000000093"),
                            Name = "Documentar y notificar incidencia de recepción de mercancía",
                            TaskCode = "TAR-0093"
                        });
                });

            modelBuilder.Entity("Sgol.Configuration.Contracts.TaskDefinitionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_id");

                    b.Property<Guid>("TaskDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_definition_id");

                    b.Property<JsonDocument>("TaskPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("task_payload");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "TaskDefinitionId")
                        .HasName("AK_task_definition_version_id_task_definition_id");

                    b.HasIndex("SupersedesId")
                        .IsUnique()
                        .HasDatabaseName("IX_task_definition_version_supersedes_id")
                        .HasFilter("supersedes_id IS NOT NULL");

                    b.HasIndex("TaskDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("IX_task_definition_version_one_live")
                        .HasFilter("status IN ('VIGENTE', 'INACTIVA_NUEVAS')");

                    b.HasIndex("ReleaseId", "TaskDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("IX_task_definition_version_release_definition");

                    b.HasIndex("TaskDefinitionId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("IX_task_definition_version_number");

                    b.ToTable("task_definition_version", null, t =>
                        {
                            t.HasCheckConstraint("CK_task_definition_version_lifecycle", "(status = 'BORRADOR' AND effective_from IS NULL AND effective_to IS NULL AND reason IS NULL AND supersedes_id IS NULL) OR (status IN ('VIGENTE','INACTIVA_NUEVAS') AND effective_from IS NOT NULL AND effective_to IS NULL AND btrim(reason) <> '') OR (status = 'SUSTITUIDA' AND effective_from IS NOT NULL AND effective_to > effective_from AND btrim(reason) <> '')");

                            t.HasCheckConstraint("CK_task_definition_version_not_self_superseding", "supersedes_id IS NULL OR supersedes_id <> id");

                            t.HasCheckConstraint("CK_task_definition_version_number", "version_no > 0");

                            t.HasCheckConstraint("CK_task_definition_version_row_version", "row_version > 0");

                            t.HasCheckConstraint("CK_task_definition_version_schema", "schema_version = 1 AND task_payload = '{}'::jsonb");

                            t.HasCheckConstraint("CK_task_definition_version_status", "status IN ('BORRADOR','VIGENTE','SUSTITUIDA','INACTIVA_NUEVAS')");
                        });
                });

            modelBuilder.Entity("Sgol.Generation.Contracts.GenerationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("ObligationId")
                        .HasColumnType("uuid")
                        .HasColumnName("obligation_id");

                    b.Property<string>("OriginReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_reference");

                    b.Property<string>("OriginType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("origin_type");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("request_hash");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("result");

                    b.Property<Guid>("RuleVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_version_id");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_generation_request_idempotency_key");

                    b.HasIndex("ObligationId")
                        .IsUnique()
                        .HasDatabaseName("UX_generation_request_obligation_id")
                        .HasFilter("obligation_id IS NOT NULL");

                    b.HasIndex("PeriodId");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("ObligationId", "Id")
                        .IsUnique();

                    b.HasIndex("RuleVersionId", "BranchId", "PeriodId", "OriginType", "OriginReference")
                        .IsUnique()
                        .HasDatabaseName("UX_generation_request_functional_key");

                    b.ToTable("generation_request", null, t =>
                        {
                            t.HasCheckConstraint("CK_generation_request_origin", "btrim(origin_type) <> '' AND btrim(origin_reference) <> ''");

                            t.HasCheckConstraint("CK_generation_request_result", "result IN ('ACEPTADA','RECUPERADA','RECHAZADA')");
                        });
                });

            modelBuilder.Entity("Sgol.Generation.Contracts.WorkObligation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset?>("ConcludedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("concluded_at");

                    b.Property<Guid?>("ConcludedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("concluded_by");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<string>("ExecutionStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("execution_status");

                    b.Property<Guid>("GenerationRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_request_id");

                    b.Property<JsonDocument>("InputPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_payload");

                    b.Property<string>("OriginReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_reference");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<Guid>("TaskDefinitionVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_definition_version_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "GenerationRequestId")
                        .HasName("AK_work_obligation_id_generation_request_id");

                    b.HasIndex("GenerationRequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_work_obligation_generation_request");

                    b.HasIndex("PeriodId");

                    b.HasIndex("TaskDefinitionVersionId");

                    b.HasIndex("BranchId", "ExecutionStatus", "DueAt");

                    b.ToTable("work_obligation", null, t =>
                        {
                            t.HasCheckConstraint("CK_work_obligation_conclusion", "(execution_status = 'PENDIENTE' AND concluded_at IS NULL AND concluded_by IS NULL) OR (execution_status = 'CONCLUIDA' AND concluded_at IS NOT NULL AND concluded_by IS NOT NULL)");

                            t.HasCheckConstraint("CK_work_obligation_execution_status", "execution_status IN ('PENDIENTE','CONCLUIDA')");

                            t.HasCheckConstraint("CK_work_obligation_origin", "btrim(origin_reference) <> ''");

                            t.HasCheckConstraint("CK_work_obligation_row_version", "row_version > 0");
                        });
                });

            modelBuilder.Entity("Sgol.Organization.Contracts.AvailabilityDayVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date")
                        .HasColumnName("local_date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_id");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("SupersedesId")
                        .IsUnique()
                        .HasFilter("supersedes_id IS NOT NULL");

                    b.HasIndex("PersonId", "BranchId", "LocalDate")
                        .IsUnique()
                        .HasFilter("status = 'VIGENTE'");

                    b.ToTable("availability_day_version", null, t =>
                        {
                            t.HasCheckConstraint("CK_availability_day_version_row_version", "row_version >= 1");

                            t.HasCheckConstraint("CK_availability_day_version_status", "status IN ('VIGENTE', 'HISTORICA')");
                        });
                });

            modelBuilder.Entity("Sgol.Organization.Contracts.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("branch", null, t =>
                        {
                            t.HasCheckConstraint("CK_branch_mvp_code", "code = 'LOR-001'");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("019d2d67-2c00-7000-8000-000000000001"),
                            Code = "LOR-001",
                            Name = "Loretta",
                            Status = "ACTIVA",
                            TimeZone = "America/Mexico_City"
                        });
                });

            modelBuilder.Entity("Sgol.Organization.Contracts.EmploymentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("PositionText")
                        .HasColumnType("text")
                        .HasColumnName("position_text");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("ShiftText")
                        .HasColumnType("text")
                        .HasColumnName("shift_text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_id");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("SupersedesId")
                        .IsUnique()
                        .HasFilter("supersedes_id IS NOT NULL");

                    b.HasIndex("PersonId", "BranchId")
                        .IsUnique()
                        .HasFilter("valid_to IS NULL");

                    b.ToTable("employment_version", null, t =>
                        {
                            t.HasCheckConstraint("CK_employment_version_interval", "valid_to IS NULL OR valid_to >= valid_from");

                            t.HasCheckConstraint("CK_employment_version_status", "status IN ('ACTIVA', 'INACTIVA')");
                        });
                });

            modelBuilder.Entity("Sgol.Organization.Contracts.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("StableCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stable_code");

                    b.HasKey("Id");

                    b.HasIndex("StableCode")
                        .IsUnique();

                    b.ToTable("person", null, t =>
                        {
                            t.HasCheckConstraint("CK_person_stable_code_not_blank", "btrim(stable_code) <> ''");
                        });
                });

            modelBuilder.Entity("Sgol.Planning.Contracts.WeekPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("DerivedStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("derived_status");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<int>("IsoWeek")
                        .HasColumnType("integer")
                        .HasColumnName("iso_week");

                    b.Property<int>("IsoYear")
                        .HasColumnType("integer")
                        .HasColumnName("iso_year");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.HasKey("Id");

                    b.HasIndex("BranchId", "IsoYear", "IsoWeek")
                        .IsUnique()
                        .HasDatabaseName("UX_week_period_branch_iso_week");

                    b.ToTable("week_period", null, t =>
                        {
                            t.HasCheckConstraint("CK_week_period_dates", "ends_on = starts_on + 6 AND EXTRACT(ISODOW FROM starts_on) = 1");

                            t.HasCheckConstraint("CK_week_period_derived_status", "derived_status IN ('VIGENTE', 'TRANSCURRIDA')");

                            t.HasCheckConstraint("CK_week_period_iso_week", "iso_week BETWEEN 1 AND 53");

                            t.HasCheckConstraint("CK_week_period_iso_year", "iso_year BETWEEN 1 AND 9999");
                        });
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Auditing.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<JsonDocument>("AfterData")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_data");

                    b.Property<JsonDocument>("BeforeData")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_data");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("RequestId")
                        .HasColumnType("text")
                        .HasColumnName("request_id");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_type");

                    b.Property<string>("SourceIpHash")
                        .HasColumnType("character(64)")
                        .HasColumnName("source_ip_hash");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId", "OccurredAt")
                        .IsDescending(false, true);

                    b.HasIndex("BranchId", "OccurredAt")
                        .IsDescending(false, true);

                    b.HasIndex("ResourceType", "ResourceId", "OccurredAt")
                        .IsDescending(false, false, true);

                    b.ToTable("audit_event", (string)null);
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("MfaEnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mfa_enrolled_at");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.DirectionBootstrapMarker", b =>
                {
                    b.Property<bool>("Singleton")
                        .HasColumnType("boolean")
                        .HasColumnName("singleton");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.HasKey("Singleton");

                    b.ToTable("direction_bootstrap", null, t =>
                        {
                            t.HasCheckConstraint("CK_direction_bootstrap_singleton", "singleton");
                        });
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.IdempotencyRecord", b =>
                {
                    b.Property<string>("Scope")
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("request_hash");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_type");

                    b.Property<int>("ResponseCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Scope", "Key");

                    b.ToTable("idempotency_record", (string)null);
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.IdentityCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.ToTable("identity_credential", (string)null);
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.RoleAssignmentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_code");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("SupersedesId");

                    b.HasIndex("UserId", "BranchId")
                        .IsUnique()
                        .HasFilter("status = 'ACTIVO'");

                    b.ToTable("role_assignment_version", null, t =>
                        {
                            t.HasCheckConstraint("CK_role_assignment_version_interval", "(status = 'ACTIVO' AND valid_to IS NULL) OR (status = 'SUSTITUIDO' AND valid_to IS NOT NULL AND valid_to >= valid_from)");

                            t.HasCheckConstraint("CK_role_assignment_version_role_code", "role_code IN ('DIRECCION', 'ADMINISTRACION', 'SUBCOORDINACION', 'PISO_VENTAS')");

                            t.HasCheckConstraint("CK_role_assignment_version_status", "status IN ('ACTIVO', 'SUSTITUIDO')");
                        });
                });

            modelBuilder.Entity("Sgol.Assignment.Contracts.EligibilityCandidate", b =>
                {
                    b.HasOne("Sgol.Assignment.Contracts.EligibilityEvaluation", null)
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Organization.Contracts.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgol.Assignment.Contracts.EligibilityEvaluation", b =>
                {
                    b.HasOne("Sgol.Generation.Contracts.WorkObligation", null)
                        .WithMany()
                        .HasForeignKey("ObligationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Configuration.Contracts.EligibilityPolicyVersion", null)
                        .WithMany()
                        .HasForeignKey("PolicyVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Organization.Contracts.Person", null)
                        .WithMany()
                        .HasForeignKey("WinnerPersonId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sgol.Configuration.Contracts.ActivationRuleVersion", b =>
                {
                    b.HasOne("Sgol.Configuration.Contracts.ActivationRuleVersion", null)
                        .WithMany()
                        .HasForeignKey("BasedOnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sgol.Configuration.Contracts.ConfigurationRelease", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Configuration.Contracts.ActivationRuleVersion", null)
                        .WithOne()
                        .HasForeignKey("Sgol.Configuration.Contracts.ActivationRuleVersion", "SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sgol.Configuration.Contracts.TaskDefinition", null)
                        .WithMany()
                        .HasForeignKey("TaskDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Configuration.Contracts.TaskDefinitionVersion", null)
                        .WithMany()
                        .HasForeignKey("TaskDefinitionVersionId", "TaskDefinitionId")
                        .HasPrincipalKey("Id", "TaskDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgol.Configuration.Contracts.CalendarDayVersion", b =>
                {
                    b.HasOne("Sgol.Organization.Contracts.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Configuration.Contracts.ConfigurationRelease", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Configuration.Contracts.CalendarDayVersion", null)
                        .WithOne()
                        .HasForeignKey("Sgol.Configuration.Contracts.CalendarDayVersion", "SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sgol.Configuration.Contracts.ConfigurationRelease", b =>
                {
                    b.HasOne("Sgol.Organization.Contracts.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Web.Infrastructure.Persistence.Bootstrap.AppUser", null)
                        .WithMany()
                        .HasForeignKey("PublishedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sgol.Configuration.Contracts.ConfigurationRelease", null)
                        .WithOne()
                        .HasForeignKey("Sgol.Configuration.Contracts.ConfigurationRelease", "SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sgol.Configuration.Contracts.EligibilityPolicyVersion", b =>
                {
                    b.HasOne("Sgol.Configuration.Contracts.EligibilityPolicyVersion", null)
                        .WithMany()
                        .HasForeignKey("BasedOnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sgol.Configuration.Contracts.ConfigurationRelease", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Configuration.Contracts.EligibilityPolicyVersion", null)
                        .WithOne()
                        .HasForeignKey("Sgol.Configuration.Contracts.EligibilityPolicyVersion", "SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sgol.Configuration.Contracts.TaskDefinition", null)
                        .WithMany()
                        .HasForeignKey("TaskDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Configuration.Contracts.TaskDefinitionVersion", null)
                        .WithMany()
                        .HasForeignKey("TaskDefinitionVersionId", "TaskDefinitionId")
                        .HasPrincipalKey("Id", "TaskDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgol.Configuration.Contracts.TaskDefinitionVersion", b =>
                {
                    b.HasOne("Sgol.Configuration.Contracts.ConfigurationRelease", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Configuration.Contracts.TaskDefinitionVersion", null)
                        .WithOne()
                        .HasForeignKey("Sgol.Configuration.Contracts.TaskDefinitionVersion", "SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sgol.Configuration.Contracts.TaskDefinition", null)
                        .WithMany()
                        .HasForeignKey("TaskDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgol.Generation.Contracts.GenerationRequest", b =>
                {
                    b.HasOne("Sgol.Organization.Contracts.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Planning.Contracts.WeekPeriod", null)
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Web.Infrastructure.Persistence.Bootstrap.AppUser", null)
                        .WithMany()
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Configuration.Contracts.ActivationRuleVersion", null)
                        .WithMany()
                        .HasForeignKey("RuleVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Generation.Contracts.WorkObligation", null)
                        .WithOne()
                        .HasForeignKey("Sgol.Generation.Contracts.GenerationRequest", "ObligationId", "Id")
                        .HasPrincipalKey("Sgol.Generation.Contracts.WorkObligation", "Id", "GenerationRequestId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sgol.Generation.Contracts.WorkObligation", b =>
                {
                    b.HasOne("Sgol.Organization.Contracts.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Generation.Contracts.GenerationRequest", null)
                        .WithOne()
                        .HasForeignKey("Sgol.Generation.Contracts.WorkObligation", "GenerationRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Planning.Contracts.WeekPeriod", null)
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Configuration.Contracts.TaskDefinitionVersion", null)
                        .WithMany()
                        .HasForeignKey("TaskDefinitionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgol.Organization.Contracts.AvailabilityDayVersion", b =>
                {
                    b.HasOne("Sgol.Organization.Contracts.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Web.Infrastructure.Persistence.Bootstrap.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Organization.Contracts.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Organization.Contracts.AvailabilityDayVersion", null)
                        .WithMany()
                        .HasForeignKey("SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sgol.Organization.Contracts.EmploymentVersion", b =>
                {
                    b.HasOne("Sgol.Organization.Contracts.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Organization.Contracts.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Organization.Contracts.EmploymentVersion", null)
                        .WithMany()
                        .HasForeignKey("SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sgol.Planning.Contracts.WeekPeriod", b =>
                {
                    b.HasOne("Sgol.Organization.Contracts.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.AppUser", b =>
                {
                    b.HasOne("Sgol.Organization.Contracts.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.IdentityCredential", b =>
                {
                    b.HasOne("Sgol.Web.Infrastructure.Persistence.Bootstrap.AppUser", null)
                        .WithOne()
                        .HasForeignKey("Sgol.Web.Infrastructure.Persistence.Bootstrap.IdentityCredential", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgol.Web.Infrastructure.Persistence.Bootstrap.RoleAssignmentVersion", b =>
                {
                    b.HasOne("Sgol.Organization.Contracts.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgol.Web.Infrastructure.Persistence.Bootstrap.RoleAssignmentVersion", null)
                        .WithMany()
                        .HasForeignKey("SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sgol.Web.Infrastructure.Persistence.Bootstrap.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
