using System.Diagnostics;
using System.Security.Cryptography.X509Certificates;
using System.Text.Json;

namespace Sgol.FrontendBrowserTests;

// Only certificates freshly generated by a fixture may enter this helper.
internal static class OwnedBrowserCertificateTrust
{
    internal static void Add(X509Certificate2 certificate)
    {
        if (Contains(certificate)) throw new InvalidOperationException("Owned certificate already present.");
        Record(certificate, "INSTALL_REQUESTED");
        try
        {
            Install(certificate);
            Record(certificate, "TRUSTED");
        }
        catch
        {
            if (!Remove(certificate)) throw new InvalidOperationException("Owned certificate installation rollback failed.");
            throw;
        }
    }

    private static void Install(X509Certificate2 certificate)
    {
        if (OperatingSystem.IsWindows())
        {
            var publicPath = Path.Combine(Path.GetTempPath(), $"sgol-front005-trust-{Guid.CreateVersion7():N}.cer");
            try
            {
                File.WriteAllBytes(publicPath, certificate.Export(X509ContentType.Cert));
                RunCertutil("-addstore", publicPath);
            }
            finally
            {
                if (File.Exists(publicPath)) File.Delete(publicPath);
            }
            if (File.Exists(publicPath)) throw new InvalidOperationException("Owned public certificate cleanup failed.");
        }
        else
        {
            using var roots = new X509Store(StoreName.Root, StoreLocation.CurrentUser);
            roots.Open(OpenFlags.ReadWrite);
            roots.Add(certificate);
        }
        if (!Contains(certificate)) throw new InvalidOperationException("Owned certificate trust installation failed.");
    }

    internal static bool Remove(X509Certificate2 certificate)
    {
        if (!Contains(certificate))
        {
            Record(certificate, "REMOVED");
            return true;
        }
        Record(certificate, "REMOVE_REQUESTED");
        if (OperatingSystem.IsWindows()) RunCertutil("-delstore", certificate.Thumbprint);
        else
        {
            using var roots = new X509Store(StoreName.Root, StoreLocation.CurrentUser);
            roots.Open(OpenFlags.ReadWrite);
            roots.Remove(certificate);
        }
        var absent = !Contains(certificate);
        Record(certificate, absent ? "REMOVED" : "CLEANUP_FAILED");
        return absent;
    }

    private static void Record(X509Certificate2 certificate, string state)
    {
        var output = Environment.GetEnvironmentVariable("SGOL_TECH_FRONT005_OUTPUT");
        if (string.IsNullOrEmpty(output)) return;
        var directory = Path.Combine(output, "owned-certificates");
        Directory.CreateDirectory(directory);
        // Public ownership metadata only. No key, PFX password or certificate contents.
        File.WriteAllText(Path.Combine(directory, certificate.Thumbprint + ".json"), JsonSerializer.Serialize(new
        {
            thumbprint = certificate.Thumbprint,
            subject = certificate.Subject,
            notBeforeUtc = certificate.NotBefore.ToUniversalTime(),
            notAfterUtc = certificate.NotAfter.ToUniversalTime(),
            state,
        }));
    }

    private static bool Contains(X509Certificate2 certificate)
    {
        using var roots = new X509Store(StoreName.Root, StoreLocation.CurrentUser);
        roots.Open(OpenFlags.ReadOnly);
        var matches = roots.Certificates.Find(X509FindType.FindByThumbprint, certificate.Thumbprint, validOnly: false);
        try { return matches.Count != 0; }
        finally { foreach (var match in matches) match.Dispose(); }
    }

    private static void RunCertutil(string operation, string ownedResource)
    {
        var start = new ProcessStartInfo(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System), "certutil.exe"))
        {
            UseShellExecute = false,
            CreateNoWindow = true,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
        };
        start.ArgumentList.Add("-user");
        start.ArgumentList.Add("-f");
        start.ArgumentList.Add(operation);
        start.ArgumentList.Add("Root");
        start.ArgumentList.Add(ownedResource);
        using var process = Process.Start(start) ?? throw new InvalidOperationException("Owned certificate command unavailable.");
        var stdout = process.StandardOutput.ReadToEndAsync();
        var stderr = process.StandardError.ReadToEndAsync();
        // Deadline for a verified trust dialog; this is not browser synchronization or a retry.
        if (!process.WaitForExit(120_000))
        {
            process.Kill();
            process.WaitForExit();
            throw new InvalidOperationException("Owned certificate command timed out.");
        }
        // Output remains in memory; do not publish certificate metadata or localized diagnostics.
        Task.WhenAll(stdout, stderr).GetAwaiter().GetResult();
        if (process.ExitCode != 0) throw new InvalidOperationException($"Owned certificate command failed: exit={process.ExitCode}.");
    }
}
